# Generated by Django 4.0.4 on 2022-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='category',
            field=models.CharField(choices=[('Café da manhã', 'Café da manhã'), ('Almoço', 'Almoço'), ('Massa', 'Massa'), ('Doce', 'Doce'), ('Sobremesa', 'Sobremesa'), ('Lanche', 'Lanche')], max_length=14, verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
