# Generated by Django 4.0.4 on 2022-06-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_receita_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='category',
        ),
    ]
