# Generated by Django 4.0.4 on 2022-06-10 16:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_receita_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='non-slug', editable=True, populate_from='author'),
        ),
    ]
