# Generated by Django 4.0.4 on 2022-06-13 20:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_receita_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='author'),
        ),
    ]
