# Generated by Django 4.0.4 on 2022-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_recipe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Publicado:'),
        ),
    ]
